### ISSUE TITLE
mvn install complate and ./elastic-tool return error 

### ISSUE THREAD

**Issue by zonshy** [hakanilter/elastic-tools#1]
mvn install complate and ./elastic-tool return error  
1. rpm -qa 
scala-2.10.6-14.module_el8.0.0+82+8ee6c375.noarch
java-1.8.0-openjdk-1.8.0.272.b10-3.el8_3.x86_64
maven-3.5.4-5.module_el8.0.0+39+6a9b6e22.noarch
spark 2.1.0

2. mvn install command execute complete and ./elastic-tool return error 
```
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: scala/collection/immutable/Map
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
        at java.lang.Class.getMethod0(Class.java:3018)
        at java.lang.Class.getMethod(Class.java:1784)
        at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:650)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:632)
Caused by: java.lang.ClassNotFoundException: scala.collection.immutable.Map
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 7 more
```

**Comment by hakanilter** [comment]
Thanks for letting me know. I have updated the code, it must be fixed now.
